name: Deploy MkDocs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Debug - List repository contents
        run: ls -R
      - name: Build English docs
        run: |
          cd mydocs-en
          mkdocs build --site-dir ../../site

      - name: Build Chinese docs
        run: |
          cd mydocs-zh-TW
          mkdocs build --site-dir ../../site/zh-TW

      - name: Debug - List site contents
        run: ls -R site/
      - name: Create .nojekyll file
        run: |
          touch site/.nojekyll
          echo "my-sharing.crystalhhc.com" > site/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true

      - name: Debug - Final site contents
        if: always()
        run: |
          ls -R site/